### ISSUE TITLE
Issue with installing plugins

### ISSUE THREAD

**Issue by jacoplane** [leonstafford/lokl#36]
Hi, I've gotten everything working in Windows 10 with WSL2 (Ubuntu 20.04 LTS). Deploying to zip works perfectly. However, when I try to install any plugin, I am getting this error: `Installation failed: Download failed. cURL error 6: Could not resolve host: downloads.wordpress.org`

I've tried restarting Docker, but no luck. Any ideas? Thanks!

Edit: I've just realized that manually downloading the plugin and then opening the zip file works, so that basically solves my problem. Still having to do this manually every time there's an update could get tedious, so still hope there's a way to fix this error.

**Comment by leonstafford** [comment]
Hi @jacoplane,

This can still happen intermittently, it seems. Last research showed a known Docker issue, which I worked around a bit, by forcing 8.8.8.8 or 1.1.1.1 DNS resolution within the containers.

I'll keep an eye out in case I encounter it again, so I can debug it locally.

For now, maybe can try restarting the site, failing that, the whole Docker service, then Windows, to see if anything helps jiggle the network routes.

**Comment by leonstafford** [comment]
I've just added templating functionality, due for next release. This allows to auto mount volumes from host into the site's container currently.

Next iteration of that will allow you to specify plugins/theme to install via template, ie, to quickly spin up 10 sites with particular plugin/theme setups.

Curious, if you use the lokl wizard to SSH into the site and run 'wp plugin install akismet', will that fail similarly to the UI, while you're seeing this network error?

**Comment by jacoplane** [comment]
Hi @leonstafford, yes using the cli gives the same error:

`/usr/html # wp plugin install akismet
Installing Akismet Spam Protection (4.1.9)
Downloading installation package from https://downloads.wordpress.org/plugin/akismet.4.1.9.zip...
Warning: Download failed. "cURL error 6: Could not resolve host: downloads.wordpress.org"
Warning: The 'akismet' plugin could not be found.
Error: No plugins installed.`

I'll do some more research tonight, I'll let you know if I find anything. Thanks!

**Comment by jacoplane** [comment]
OK well I did what you suggested and added  `"dns": ["8.8.8.8"]` to the Docker daemon.json file and now I am able to install plugins!

**Comment by leonstafford** [comment]
Great to hear, @jacoplane!

That was all you, I hadn't pointed you to daemon.json file :) 

I may reopen/rename this issue, if I hear more reports from users. For now, I'll know to point anyone affected here, so big thanks!

Hope Lokl is useful for you. Please share any feature requests/issues as they come up.

Cheers
